/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 michael.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Michael(props) {
  const { nodes, materials } = useGLTF('/michael.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fesmk55'].geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/michael.gltf')
